# Ubuntu 18.04 Bionic support
os:
    - linux
dist: bionic

language: python
python:
    - "3.8"

# Install the codecov pip dependency
install:
  - pip3 install codecov

# Run the unit tests
script:
  - coverage run tests/test_lopu.py

# Push the results back to codecov
after_success:
  - codecov
